---
################################################################################################
# Create Instances in GCE                                                                      #
#                                                                                              #
# By Robert J. Calva - Red Hat LATAM - 2017                                                    #
#                                                                                              #
# Variable examples:                                                                           #
#                                                                                              #
#     zone: us-central1-a                                                                      #
#     instance_names: my-webtest-instance1,my-webtest-instance2,my-webtest-instance3           #
#     machine_type: g1-small                                                                   #
#     image: centos-7-v20170523                                                                #
#     dns_zone: workshop.example.com                                                           #
#                                                                                              #
#                                                                                              #
# Enjoy!                                                                                       #
################################################################################################
- name: Create Instances in GCE
  hosts: localhost
  gather_facts: True
  connection: local
  
  tasks:
  - name: Create an Instance based on image "{{ image }}"  
    gce:
      instance_names: "{{ instance_name }}"
      zone: "{{ zone }}"
      machine_type: "{{ machine_type }}"
      image: "{{ image }}"
      state: present
      preemptible: true
#      disk_size: "{{disk_size}}"
      tags: http-server,https-server,cockpit-rule,jboss-rule
    register: gce

  - set_stats:
      data:
        gce_instance_data: "{{ gce.instance_data }}"
      per_host: no
