- name: Delete Instances in GCE
  hosts: localhost
  gather_facts: yes
  connection: local

  tasks:
  - name: Deleting Instances "{{ instance_name }}"
    gce:
      instance_names: "{{ instance_name }}"
      zone: "{{zone}}"
      state: absent
