---
################################################################################################
# Create Instances in GCE                                                                      #
#                                                                                              #
# By Robert J. Calva - Red Hat LATAM - 2017                                                    #
#                                                                                              #
# Variable examples:                                                                           #
#                                                                                              #
#     zone: us-central1-a                                                                      #
#     instance_name: my-webtest-instance1,my-webtest-instance2,my-webtest-instance3           #
#     machine_type: g1-small                                                                   #
#     image: centos-7-v20170523                                                                #
#     dns_zone: workshop.example.com                                                           #
#                                                                                              #
#                                                                                              #
# Enjoy!                                                                                       #
################################################################################################
- name: Create Instances in GCE
  hosts: localhost
  gather_facts: True
  connection: local
  
  tasks:
  - name: Create an Instance based on image "{{ image }}"  
    gce:
      instance_name: "{{ instance_name }}"
      zone: "{{ zone }}"
      machine_type: "{{ machine_type }}"
      image: "{{ image }}"
      state: present
      preemptible: true
#      disk_size: "{{disk_size}}"
      tags: http-server,https-server
    register: gce

  - name: Record "{{ instance_name }}" within "{{ dns_zone }}"
    gcdns_record:
      zone: "{{ dns_zone }}" 
      record: "{{ instance_name }}.{{ dns_zone }}"
      type: A
      overwrite: true
      value: "{{ host }}"
      
  - set_stats:
    data:
      gce_instance_data: "{{ gce.instance_data }}"
    per_host: no
