- name: Install Software on Windows Instances in GCE
  hosts: all
  gather_facts: False  
  
  tasks: 
   - name: Install "{{ software }}" on Windows Instance
     win_feature:
       name: "{{ software }}"
       state: present
       include_sub_features: False
       include_management_tools: True
     register: software
     
   - name: reboot if installing "{{ software }}" feature requires it
     win_reboot:
     when: software.reboot_required
