---
- name: restart jboss 
  service: name=jboss state=restarted

- name: restart iptables
  service: name=iptables state=restarted

- name: restart firewalld
  service: name=firewalld state=restarted
